name = "websocket-worker"  # todo

workers_dev = true
compatibility_date = "2023-02-05"

main = "build/worker/shim.mjs"

[build]
command = "cargo install -q worker-build && worker-build --release"


[durable_objects]
bindings = [
  { name = "CHATROOM", class_name = "Chatroom" } # the `class_name` uses the Rust struct identifier name
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Chatroom"]